[package]
name = "terminalchat"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.16.0", features = ["v4"] }
chrono = { version = "0.4.41"  }

[[bin]]
name = "terminalchat"
path = "main.rs"
